EduQuiz/Models/EF/EduQuizFavorite.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EduQuiz.Models.EF
{
    [Table("EduQuizFavorite")]
    public class EduQuizFavorite
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int? UserId { get; set; }

        [ForeignKey("UserId")]
        public virtual User User { get; set; }
        public int? EduQuizId { get; set; }

        [ForeignKey("EduQuizId")]
        public virtual EduQuiz EduQuiz { get; set; }
    }
}

EduQuiz/Controllers/LibraryController.cs
using EduQuiz.DatabaseContext;
using EduQuiz.Models;
using EduQuiz.Models.EF;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using static NuGet.Packaging.PackagingConstants;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace EduQuiz.Controllers
{
    [CustomAuthorize("User")]
    public class LibraryController : Controller
    {
        private readonly EduQuizDBContext _context;
        public LibraryController(EduQuizDBContext context)
        {
            _context = context;
        }
        public IActionResult _PartialFolders()
        {
            var authCookie = Request.Cookies["acToken"];

            if (authCookie == null)
            {
                return RedirectToAction("Login", "Accout");
                
            }
            var tokenHandler = new JwtSecurityTokenHandler();
            var jwtToken = tokenHandler.ReadJwtToken(authCookie);
            var userId = jwtToken.Claims.FirstOrDefault(c => c.Type == "UserId")?.Value;
            int iduser = int.Parse(userId ?? "1");
            var model = _context.Folders
                .Where(f => f.UserId == iduser)
                .OrderBy(f => f.Name)
                .ToList();
            return PartialView("_PartialFolders", model);
        }
        [Route("my-library/eduquizs/all")]
        public async Task<IActionResult> Index()
        {
            var authCookie = Request.Cookies["acToken"];
            int iduser = 0;
            if (authCookie == null)
            {
                return RedirectToAction("Login", "Accout");
                
            }
            var tokenHandler = new JwtSecurityTokenHandler();
            var jwtToken = tokenHandler.ReadJwtToken(authCookie);
            var userId = jwtToken.Claims.FirstOrDefault(c => c.Type == "UserId")?.Value;
            iduser = int.Parse(userId ?? "1");
            var user = await _context.Users.FindAsync(iduser);
            if (user == null)
            {
                return RedirectToAction("Login", "Accout");
            }
            await EnsureFolderExistsAsync(user.Id);
            var folders = _context.Folders
              .Where(f => f.UserId == iduser)
              .OrderBy(f => f.Name)
              .ToList();

            ViewBag.Folders = folders;
            var listEduQuizByUser = await _context.EduQuizs
                    .Where(d => d.UserId == user.Id && d.Type == 1 && d.Status == true)
                    .Include(e => e.Questions)
                    .OrderByDescending(d => d.UpdateAt)
                    .ToListAsync();
            ViewBag.Data = JsonConvert.SerializeObject(new { UserName = user.Username, Avatar = user.ProfilePicture });
            return View(listEduQuizByUser);
        }
        [Route("my-library/eduquizs/share")]
        public async Task<IActionResult> EduQuizShare()
        {
            var authCookie = Request.Cookies["acToken"];
            int iduser = 0;
            if (authCookie == null)
            {
                return RedirectToAction("Login", "Accout");

            }
            var tokenHandler = new JwtSecurityTokenHandler();
            var jwtToken = tokenHandler.ReadJwtToken(authCookie);
            var userId = jwtToken.Claims.FirstOrDefault(c => c.Type == "UserId")?.Value;
            iduser = int.Parse(userId ?? "1");
            var user = await _context.Users.FindAsync(iduser);
            if (user == null)
            {
                return RedirectToAction("Login", "Accout");
            }
            await EnsureFolderExistsAsync(user.Id);
            var folders = _context.Folders
              .Where(f => f.UserId == iduser)
              .OrderBy(f => f.Name)
              .ToList();

            ViewBag.Folders = folders;
            var listEduQuizShare = await (from s in _context.ShareGroups 
                                          join gm in _context.GroupMembers on s.GroupId equals gm.GroupId
                                          join e in _context.EduQuizs on s.EduQuizId equals e.Id
                                          join u in _context.Users on e.UserId equals u.Id
                                          where gm.UserId == iduser
                                          select new EduQuizView
                                          {
                                              Id = e.Id,
                                              Avatar = u.ProfilePicture,
                                              Image = e.ImageCover,
                                              SumQuestion = _context.Questions.Count(q=>q.EduQuizId == e.Id),
                                              Title = e.Title,
                                              Uuid= e.Uuid,
                                              UserName = u.Username
                                          }).ToListAsync();
            return View(listEduQuizShare);
        }
        [Route("my-library/eduquizs/favorite")]
        public async Task<IActionResult> EduQuizFavorite()
        {
            var authCookie = Request.Cookies["acToken"];
            int iduser = 0;
            if (authCookie == null)
            {
                return RedirectToAction("Login", "Accout");

            }
            var tokenHandler = new JwtSecurityTokenHandler();
            var jwtToken = tokenHandler.ReadJwtToken(authCookie);
            var userId = jwtToken.Claims.FirstOrDefault(c => c.Type == "UserId")?.Value;
            iduser = int.Parse(userId ?? "1");
            var user = await _context.Users.FindAsync(iduser);
            if (user == null)
            {
                return RedirectToAction("Login", "Accout");
            }
            await EnsureFolderExistsAsync(user.Id);
            var folders = _context.Folders
              .Where(f => f.UserId == iduser)
              .OrderBy(f => f.Name)
              .ToList();

            ViewBag.Folders = folders;
            var listEduQuizShare = await (from s in _context.EduQuizFavorite
                                          join e in _context.EduQuizs on s.EduQuizId equals e.Id
                                          join u in _context.Users on e.UserId equals u.Id
                                          where s.UserId == iduser
                                          select new EduQuizView
                                          {
                                              Id = e.Id,
                                              Avatar = u.ProfilePicture,
                                              Image = e.ImageCover,
                                              SumQuestion = _context.Questions.Count(q => q.EduQuizId == e.Id),
                                              Title = e.Title,
                                              Uuid = e.Uuid,
                                              UserName = u.Username
                                          }).ToListAsync();
            return View(listEduQuizShare);
        }
        [Route("my-library/eduquizs/drafts")]
        public async Task<IActionResult> EduQuizDraft()
        {
            var authCookie = Request.Cookies["acToken"];
            int iduser = 0;
            if (authCookie == null)
            {
                return RedirectToAction("Login", "Accout");
                
            }
            var tokenHandler = new JwtSecurityTokenHandler();
            var jwtToken = tokenHandler.ReadJwtToken(authCookie);
            var userId = jwtToken.Claims.FirstOrDefault(c => c.Type == "UserId")?.Value;
            iduser = int.Parse(userId ?? "1");
            var user = await _context.Users.FindAsync(iduser);
            if (user == null)
            {
                return RedirectToAction("Login", "Accout");
            }
            await EnsureFolderExistsAsync(user.Id);
            var folders = _context.Folders
                .Where(f => f.UserId == iduser)
                .OrderBy(f => f.Name)
                .ToList();

            ViewBag.Folders = folders;
            var listEduQuizByUser = await _context.EduQuizs
                    .Where(d => d.UserId == user.Id && d.Type == 0 && d.Status == true)
                    .Include(e => e.Questions)
                    .OrderByDescending(d => d.UpdateAt)
                    .ToListAsync();
            ViewBag.Data = JsonConvert.SerializeObject(new { UserName = user.Username, Avatar = user.ProfilePicture });
            return View(listEduQuizByUser);
        }
        [Route("my-library/eduquizs/{id:guid}")]
        public async Task<IActionResult> LibrarybyFolder(Guid id)
        {
            var authCookie = Request.Cookies["acToken"];
            if (authCookie == null)
            {
                return RedirectToAction("Login", "Accout");
            }
            var tokenHandler = new JwtSecurityTokenHandler();
            var jwtToken = tokenHandler.ReadJwtToken(authCookie);
            var userId = jwtToken.Claims.FirstOrDefault(c => c.Type == "UserId")?.Value;
            int iduser = int.Parse(userId ?? "1");
            var user = await _context.Users.FindAsync(iduser);
            if (user == null)
            {
                return RedirectToAction("Login", "Accout");
            }
            var folders = _context.Folders
                .Where(f => f.UserId == iduser)
                .OrderBy(f => f.Name)
                .ToList();
            // Tìm folder hiện tại dựa trên `Uuid`
            var selectedFolder = folders.FirstOrDefault(f => f.Uuid == id);
            if (selectedFolder == null)
            {
                return RedirectToAction("Error404", "Home");
            }
            var eduQuizByFolder = _context.QuizFolders
                 .Where(qf => qf.FolderId == selectedFolder.Id)

EduQuiz/Views/Library/EduQuizFavorite.cshtml
@{
    Layout = "_LayoutUser";
    ViewBag.Title = "EduQuiz yêu thích";
    @model ICollection<EduQuiz.Models.EduQuizView>;
    @using Microsoft.AspNetCore.Http
    @inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
    var currentPath = HttpContextAccessor.HttpContext.Request.Path.Value;
}
@section styles {
    <link href="~/src/css/library.css" rel="stylesheet" />
}
<div class="content" style="padding:0;margin-top:63px;">
    <div class="layout-library">
        <div class="col-md-3 sidebar-wrapper__library" style="min-height:400px;padding:0;">
            <div class="layout-card" style="padding:0;margin:0;height:calc(100vh - 63px) ">
                <div class="sidebar-wrapper__library-Block">
                    <ul class="sidebar-Link__Container">
                        <li class="sidebar-Link__Wrapper">
                            <a class="@(string.IsNullOrEmpty(currentPath) || currentPath == "/my-library/eduquizs/all" ? "active" : "")" href="@Url.Action("Index","Library")">
                                <span class="sidebar-Link__Icon">
                                    <svg viewBox="0 0 32 32" focusable="false" stroke="none" stroke-width="0" aria-hidden="true"><title>Icon</title><path d="M10,20.6c0-0.9,0.7-1.6,1.6-1.6s1.6,0.7,1.6,1.6s-0.7,1.6-1.6,1.6S10,21.5,10,20.6z M11.5,9.8l-2,3.2h4  L11.5,9.8z M26,9v14c0,1.7-1.3,3-3,3H9c-1.7,0-3-1.3-3-3V9c0-1.7,1.3-3,3-3h14C24.7,6,26,7.3,26,9z M15,17H8v6c0,0.6,0.4,1,1,1h6V17  z M15,8H9C8.4,8,8,8.4,8,9v6h7V8z M24,17h-7v7h6c0.6,0,1-0.4,1-1V17z M24,9c0-0.6-0.4-1-1-1h-6v7h7V9z M22,19h-3v3h3V19z M18.5,11.5  l2,2l2-2l-2-2L18.5,11.5z" style="fill: rgb(110, 110, 110);"></path></svg>
                                </span>
                                <span class="ml-2">EduQuizs</span>
                            </a>
                        </li>
                    </ul>
                    <div class="library-sidebar__Separator"></div>
                    <div id="partialfolder-container">
                        <partial name="_PartialFolders" model="@ViewBag.Folders" />
                    </div>
                </div>
            </div>
        </div>
        <div class="library-layout__Content">
            <div class="library-eduquiz__Content">
                <div class="library-eduquiz__Filter">
                    <partial name="_TabLibrary" />
                    <div class="library-eduquiz__TextFilterWrapper">
                        <div class="styles__TextField">
                            <input class="input__Search" placeholder="Tìm kiếm" onkeyup="filterCards()" />
                            <span class="icon_Field"><svg viewBox="0 0 32 32" focusable="false" stroke="none" stroke-width="0" aria-hidden="true"><title>Icon</title><path d="M25.707,24.293 L20.314,18.9 C21.403,17.504 22,15.799 22,14 C22,11.863 21.167,9.854 19.656,8.344 C18.146,6.832 16.137,6 14,6 C11.863,6 9.854,6.832 8.344,8.344 C6.833,9.854 6,11.863 6,14 C6,16.137 6.833,18.146 8.344,19.656 C9.854,21.168 11.863,22 14,22 C15.799,22 17.504,21.404 18.9,20.314 L24.293,25.706 L25.707,24.293 Z M14,20 C12.397,20 10.891,19.376 9.758,18.243 C8.624,17.11 8,15.603 8,14 C8,12.398 8.624,10.891 9.758,9.758 C10.891,8.624 12.397,8 14,8 C15.603,8 17.109,8.624 18.242,9.758 C19.376,10.891 20,12.398 20,14 C20,15.603 19.376,17.11 18.242,18.243 C17.109,19.376 15.603,20 14,20 Z" style="fill: rgb(110, 110, 110);"></path></svg></span>
                        </div>
                    </div>
                </div>
                @if (Model.Count != 0)
                {
                    <div class="eduquiz-list__Content">

                        @foreach (var item in Model)
                        {
                            <div class="styles__BaseCard">
                                <div class="link-action" data-question="@item.Uuid">
                                    <div class="styles__Image" style="@($"background: url({item.Image}) center center / cover no-repeat;")">
                                        <span class="styles__Questions">@item.SumQuestion câu hỏi</span>
                                    </div>
                                    <div class="styles__BaseCard_Body">
                                        <div class="styles__BaseCard_Body flex-row">
                                            <h3 id="title-@item.Id" class="styles__BaseCard_Body-title">@(item.Title != "" ? item.Title : "Đặt tên cho EduQuiz")</h3>
                                        </div>
                                        <div class="styles__BaseCard_Body Basecard-footer">
                                            <div class="styles-InfoUser">
                                                <div class="profile-imageUser" style="@($"background: url({@item.Avatar}) center center / cover no-repeat;")"></div>
                                                <span>@item.UserName</span>
                                            </div>
                                            <div class="styles_eduquizInfo justify-content-center">
                                                <a href="@Url.Action("Index","AdminPlayEduQuiz",new {quizId = item.Uuid})" class="styles__eduquizInfo-Btn" style="background: rgb(19, 104, 206);margin:0 4px;">Chơi ngay</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                }
                else
                {
                    <div class="empty-prompt__Container">
                        <img src="/src/img/empty-prompt.svg" style="max-width: 100%;max-height: 105px; margin-bottom: 8px;" />
                        <div>Ở đây có vẻ rất trống rỗng, Bạn không có EduQuiz nào được chia sẻ!.</div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script>

</script>
<script src="~/src/js/mainlibrary.js"></script>

EduQuiz/Views/Library/EduQuizShare.cshtml
@{
    Layout = "_LayoutUser";
    ViewBag.Title = "EduQuiz bản nháp";
    @model ICollection<EduQuiz.Models.EduQuizView>;
    @using Microsoft.AspNetCore.Http
    @inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
    var currentPath = HttpContextAccessor.HttpContext.Request.Path.Value;
}
@section styles {
    <link href="~/src/css/library.css" rel="stylesheet" />
}
<div class="content" style="padding:0;margin-top:63px;">
    <div class="layout-library">
        <div class="col-md-3 sidebar-wrapper__library" style="min-height:400px;padding:0;">
            <div class="layout-card" style="padding:0;margin:0;height:calc(100vh - 63px) ">
                <div class="sidebar-wrapper__library-Block">
                    <ul class="sidebar-Link__Container">
                        <li class="sidebar-Link__Wrapper">
                            <a class="@(string.IsNullOrEmpty(currentPath) || currentPath == "/my-library/eduquizs/all" ? "active" : "")" href="@Url.Action("Index","Library")">
                                <span class="sidebar-Link__Icon">
                                    <svg viewBox="0 0 32 32" focusable="false" stroke="none" stroke-width="0" aria-hidden="true"><title>Icon</title><path d="M10,20.6c0-0.9,0.7-1.6,1.6-1.6s1.6,0.7,1.6,1.6s-0.7,1.6-1.6,1.6S10,21.5,10,20.6z M11.5,9.8l-2,3.2h4  L11.5,9.8z M26,9v14c0,1.7-1.3,3-3,3H9c-1.7,0-3-1.3-3-3V9c0-1.7,1.3-3,3-3h14C24.7,6,26,7.3,26,9z M15,17H8v6c0,0.6,0.4,1,1,1h6V17  z M15,8H9C8.4,8,8,8.4,8,9v6h7V8z M24,17h-7v7h6c0.6,0,1-0.4,1-1V17z M24,9c0-0.6-0.4-1-1-1h-6v7h7V9z M22,19h-3v3h3V19z M18.5,11.5  l2,2l2-2l-2-2L18.5,11.5z" style="fill: rgb(110, 110, 110);"></path></svg>
                                </span>
                                <span class="ml-2">EduQuizs</span>
                            </a>
                        </li>
                    </ul>
                    <div class="library-sidebar__Separator"></div>
                    <div id="partialfolder-container">
                        <partial name="_PartialFolders" model="@ViewBag.Folders" />
                    </div>
                </div>
            </div>
        </div>
        <div class="library-layout__Content">
            <div class="library-eduquiz__Content">
                <div class="library-eduquiz__Filter">
                    <partial name="_TabLibrary" />
                    <div class="library-eduquiz__TextFilterWrapper">
                        <div class="styles__TextField">
                            <input class="input__Search" placeholder="Tìm kiếm" onkeyup="filterCards()" />
                            <span class="icon_Field"><svg viewBox="0 0 32 32" focusable="false" stroke="none" stroke-width="0" aria-hidden="true"><title>Icon</title><path d="M25.707,24.293 L20.314,18.9 C21.403,17.504 22,15.799 22,14 C22,11.863 21.167,9.854 19.656,8.344 C18.146,6.832 16.137,6 14,6 C11.863,6 9.854,6.832 8.344,8.344 C6.833,9.854 6,11.863 6,14 C6,16.137 6.833,18.146 8.344,19.656 C9.854,21.168 11.863,22 14,22 C15.799,22 17.504,21.404 18.9,20.314 L24.293,25.706 L25.707,24.293 Z M14,20 C12.397,20 10.891,19.376 9.758,18.243 C8.624,17.11 8,15.603 8,14 C8,12.398 8.624,10.891 9.758,9.758 C10.891,8.624 12.397,8 14,8 C15.603,8 17.109,8.624 18.242,9.758 C19.376,10.891 20,12.398 20,14 C20,15.603 19.376,17.11 18.242,18.243 C17.109,19.376 15.603,20 14,20 Z" style="fill: rgb(110, 110, 110);"></path></svg></span>
                        </div>
                    </div>
                </div>
                @if (Model.Count != 0)
                {
                    <div class="eduquiz-list__Content">

                        @foreach (var item in Model)
                        {
                            <div class="styles__BaseCard">
                                <div class="link-action" data-question="@item.Uuid">
                                    <div class="styles__Image" style="@($"background: url({item.Image}) center center / cover no-repeat;")">
                                        <span class="styles__Questions">@item.SumQuestion câu hỏi</span>
                                    </div>
                                    <div class="styles__BaseCard_Body">
                                        <div class="styles__BaseCard_Body flex-row">
                                            <h3 id="title-@item.Id" class="styles__BaseCard_Body-title">@(item.Title != "" ? item.Title : "Đặt tên cho EduQuiz")</h3>
                                        </div>
                                        <div class="styles__BaseCard_Body Basecard-footer">
                                            <div class="styles-InfoUser">
                                                <div class="profile-imageUser" style="@($"background: url({@item.Avatar}) center center / cover no-repeat;")"></div>
                                                <span>@item.UserName</span>
                                            </div>
                                            <div class="styles_eduquizInfo justify-content-center">
                                                <a href="@Url.Action("Index","AdminPlayEduQuiz",new {quizId = item.Uuid})" class="styles__eduquizInfo-Btn" style="background: rgb(19, 104, 206);margin:0 4px;">Chơi ngay</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                }
                else
                {
                    <div class="empty-prompt__Container">
                        <img src="/src/img/empty-prompt.svg" style="max-width: 100%;max-height: 105px; margin-bottom: 8px;" />
                        <div>Ở đây có vẻ rất trống rỗng, Bạn không có EduQuiz nào được chia sẻ!.</div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script>
    
</script>
<script src="~/src/js/mainlibrary.js"></script>

EduQuiz/Views/Library/_PartialFolders.cshtml
@{
    @using Microsoft.AspNetCore.Http
    @inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
    @model ICollection<EduQuiz.Models.EF.Folder>;
    var currentPath = HttpContextAccessor.HttpContext.Request.Path.Value;
}
<div class="sidebar-Link__Container">
    <div class="sidebar-folders mt-3">
        @{
            var folderRoot = Model.OrderBy(f => f.Id).FirstOrDefault();
        }
        <div class="sidebar-folders__Root @(string.IsNullOrEmpty(currentPath) || currentPath == $"/my-library/eduquizs/{folderRoot.Uuid}" ? "active" : "")">
            <a style="color:#333;text-decoration:none;padding:8px 0" href="@Url.Action("LibrarybyFolder","Library",new{id = folderRoot.Uuid})">
                <span class="sidebar-Link__Icon">
                    <svg viewBox="0 0 32 32" focusable="false" stroke="none" stroke-width="0" aria-hidden="true"><title>Icon</title><path d="M20 13C20 15.209 18.209 17 16 17C13.791 17 12 15.209 12 13C12 10.791 13.791 9 16 9C18.209 9 20 10.791 20 13ZM23.739 22.323C23.114 20.186 21.35 18.534 19.133 18.11C18.22 18.671 17.149 19 16 19C14.851 19 13.78 18.671 12.867 18.11C10.65 18.534 8.886 20.186 8.261 22.323C6.85 20.599 6 18.397 6 16C6 10.486 10.486 6 16 6C21.514 6 26 10.486 26 16C26 18.397 25.15 20.599 23.739 22.323ZM16 4C9.373 4 4 9.373 4 16C4 22.627 9.373 28 16 28C22.627 28 28 22.627 28 16C28 9.373 22.627 4 16 4Z" style="fill: rgb(110, 110, 110);"></path></svg>
                </span>
                <span class="ml-2">Thư mục của bạn</span>
            </a>
            <button class="add-folders">
                <i class="fa fa-plus" aria-hidden="true"></i>
            </button>
        </div>
        <div id="addfolder-wrapper" class="sidebar-Link__Wrapper ml-4 d-none">
            <div class="folder-content">
                <span class="sidebar-Link__Icon" style="width: 20px;height: 20px;margin-left:4px">
                    <svg viewBox="0 0 32 32" focusable="false" stroke="none" stroke-width="0" aria-hidden="true"><title>Icon</title><path d="M17,15 L13,15 L13,19 C13,19.553 12.552,20 12,20 C11.448,20 11,19.553 11,19 L11,15 L7,15 C6.448,15 6,14.553 6,14 C6,13.447 6.448,13 7,13 L11,13 L11,9 C11,8.447 11.448,8 12,8 C12.552,8 13,8.447 13,9 L13,13 L17,13 C17.552,13 18,13.447 18,14 C18,14.553 17.552,15 17,15 M22,5 L12,5 L10.553,3.105 C10.214,2.428 9.521,2 8.764,2 L1,2 C0.447,2 0,2.447 0,3 L0,21 C0,22.104 0.896,23 2,23 L22,23 C23.104,23 24,22.104 24,21 L24,7 C24,5.896 23.104,5 22,5" style="fill: rgb(110, 110, 110);"></path></svg>
                </span>
                <div class="position-relative">
                    <input data-id="@folderRoot.Id" class="input__add-folder" placeholder="Thư mục mới" maxlength="255" />
                </div>
            </div>
        </div>
        @foreach (var item in Model.Where(f => f.Id != folderRoot?.Id && f.ParentFolderId == folderRoot.Id))
        { 
            <div class="sidebar-Link__Wrapper ml-4">
                <a href="@Url.Action("LibrarybyFolder","Library",new{id = item.Uuid})" class="@(string.IsNullOrEmpty(currentPath) || currentPath == $"/my-library/eduquizs/{item.Uuid}" ? "active" : "")">
                    <span class="sidebar-Link__Icon">
                        <svg viewBox="0 0 32 32" focusable="false" stroke="none" stroke-width="0" aria-hidden="true"><title>Icon</title><path d="M24,11 C25.103,11 26,11.898 26,13 L26,23 C26,24.103 25.103,25 24,25 L8,25 C6.897,25 6,24.103 6,23 L6,10 C6,8.898 6.897,8 8,8 L12.5,8 C13.126,8 13.725,8.299 14.1,8.8 L15.75,11 L24,11 Z M8,23 L24.001,23 L24,13 L15.75,13 C15.124,13 14.525,12.701 14.15,12.2 L12.5,10 L8,10 L8,23 Z" style="fill: rgb(110, 110, 110);"></path></svg>
                    </span>
                    <span class="ml-2">@item.Name</span>
                </a>
            </div>
        }
    </div>
</div>

EduQuiz/Views/Library/_TabLibrary.cshtml
@{
    @using Microsoft.AspNetCore.Http
    @inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
    var currentPath = HttpContextAccessor.HttpContext.Request.Path.Value;
    var folderid = 1;
}
<div class="eduquiz-root__Tabs-Wrapper">
    <div class="eduquiz-root__Tabs">
        <a href="@Url.Action("Index","Library")" class="@(string.IsNullOrEmpty(currentPath) || currentPath == "/my-library/eduquizs/all" ? "active" : "")">Gần đây</a>
    </div>
    <div class="eduquiz-root__Tabs">
        <a id="tab_draft" href="@Url.Action("EduQuizDraft","Library")" class="@(string.IsNullOrEmpty(currentPath) || currentPath == "/my-library/eduquizs/drafts" ? "active" : "")">Bản nháp</a>
    </div>
    <div class="eduquiz-root__Tabs">
        <a href ="@Url.Action("EduQuizFavorite", "Library")" class="@(string.IsNullOrEmpty(currentPath) || currentPath == "/my-library/eduquizs/favorite" ? "active" : "")">Yêu thích</a>
    </div>
    <div class="eduquiz-root__Tabs">
        <a href="@Url.Action("EduQuizShare","Library")" class="@(string.IsNullOrEmpty(currentPath) || currentPath == "/my-library/eduquizs/share" ? "active" : "")">Chia sẻ với bạn</a>
    </div>
</div>
<script>
    $(".eduquiz-root__Tabs a").click(function (event) {
        if ($(this).hasClass("active")) {
            event.preventDefault();
        }
    })
</script>